language: generic 
sudo: required 

services:
  - docker 

before_install:
  - docker build -t sujnanarai/docker-react-elastic-beanstalk -f Dockerfile.dev . 

script:
  - docker run -e CI=true sujnanarai/docker-react-elastic-beanstalk npm run test
